---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "xperimentor-deployment"
  namespace: "default"
  labels:
    app: "xperimentor-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "xperimentor-deployment"
  template:
    metadata:
      labels:
        app: "xperimentor-deployment"
    spec:
      containers:
      - name: "xperimentor-container"
        image: "mpacheco95/xperimentor:latest"
        ports:
        - containerPort: 3000

